### ISSUE TITLE
Javadoc details

### ISSUE THREAD

**Issue by chinnonae** [OOP2018/guessing-game-Newaz2542#1]
You've done a great job. 👍
But there's something you may miss.  

`@return` is missing

https://github.com/OOP2018/guessing-game-Newaz2542/blob/2feda09d045bcafd6f35f6fb2216c487cdae2096/src/VichakornGame.java#L64-L77

No Javadoc
https://github.com/OOP2018/guessing-game-Newaz2542/blob/2feda09d045bcafd6f35f6fb2216c487cdae2096/src/NumberGame.java#L70-L72

**Comment by Vichacorn** [comment]
Thank you. I fixed it.
